config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beerclubs
  resources :users do
    post 'toggle_account', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end  
  resources :places, only: [:index, :show]
  

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'singin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'

  get 'beerlist', to:'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  resources :styles

  

end

app/models/user.rb
class User < ActiveRecord::Base
include RatingAverage
    validates :username, uniqueness: true,
                         length: { minimum: 3 }
    validates :username, length: { maximum: 15 }
    validates :password, length: { minimum: 4 } 
    validates :password, format: { with:/(?=.*[A-Z])/ }    

	has_many :ratings, dependent: :destroy
	has_many :beers, through: :ratings

	has_many :memberships, dependent: :destroy
	has_many :beerclubs, through: :memberships

	has_secure_password



  def self.top(n)     
   

   #i=0
   #num=n
   #top_raters=[]

   #while i<num do
    top_raters = User.all.group_by{|u| u.ratings.count}.sort.reverse.map{|x,y| y}.take(3)
    #i+=1     
    
   #end
   #return top_raters
   #User.all.group_by{|u| u.ratings.count}.sort.reverse
   #User.all.group_by{|u| u.ratings.count}.sort.reverse.map{|x,y| y}
   #User.all.map { |u| u.ratings.count }
   #User.includes(:ratings).group_by{|u| u.ratings.count}


  end

	def favorite_beer
		return nil if ratings.empty?
		#ratings.order(score: :desc).limit(1).first.beer
    ratings.sort_by{ |r| r.score }.last.beer
	end

	def favorite_style
    return nil if ratings.empty?

    rated = ratings.map{ |r| r.beer.style }.uniq
    rated.sort_by { |style| -rating_of_style(style) }.first
  end

  def favorite_brewery
    return nil if ratings.empty?

    rated = ratings.map{ |r| r.beer.brewery }.uniq
    rated.sort_by { |brewery| -rating_of_brewery(brewery) }.first
  end

  private

  def rating_of_style(style)
    ratings_of = ratings.select{ |r| r.beer.style==style }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end

  def rating_of_brewery(brewery)
    ratings_of = ratings.select{ |r| r.beer.brewery==brewery }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if current_user==@user
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_account
    user = User.find(params[:id])
    user.update_attribute :lukittu, (not user.lukittu)

    new_status = user.lukittu? ? "account frozen" : "active"

    redirect_to :back, notice:"user status changed to #{new_status}"

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!--<h1>Editing User</h1> -->
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td><%= user.favorite_beer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
<!--  <strong>Username:</strong>  -->
  <h1><strong><%= @user.username %></strong> <% if @user.lukittu %><a class="bg-info">account frozen</a><% end %></h1>
  

</p>

<p>
	Has made <%= pluralize(@user.ratings.count, 'rating') %>,
	
	average <%=  round(@user.average_rating) %>
	
</p>

<ul>
	<% @user.ratings.each do |rating| %>
	<li> <%= rating %> 
		<% if @user == current_user %>
		  <%= link_to 'delete', rating_path(rating.id), method: :delete, data: { confirm: 'are you sure??' } %>
		  <% end %>
	</li>
	<% end %>
</ul>

<ul>
	<strong>Memberships</strong>
	<% @user.memberships.each do |membership| %>
	<li> <%= membership %>
	</li>
	<% end %>

</ul>

<% if not @user.lukittu %>
<%= link_to "froze account", toggle_account_user_path(@user.id), method: :post, class: "btn btn-primary" %>
<% else %>
<%= link_to "reactivate account", toggle_account_user_path(@user.id), method: :post, class: "btn btn-warning" %>
<% end %>

<% if @user==current_user%>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Destroy', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', users_path %>
<% else %>
<%= link_to 'Back', users_path %>
<% end %>