config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beerclubs
  resources :users do
    post 'toggle_account', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end  
  resources :places, only: [:index, :show]
  

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'singin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'

  get 'beerlist', to:'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#list'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  resources :styles

  

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
include RatingAverage

	has_many :beers, dependent: :destroy
	has_many :ratings, through: :beers

	validates :name, presence: true
	validates :year, numericality: { greater_than_or_equal_to: 1042,
	                                 only_integer: true }

    validate :current_year

  def current_year
    if year > Time.now.year
    	errors.add(:year, "ei käy")
    end
  end

    scope :active, -> { where active:true }
    scope :retired, -> { where active:[nil, false] }

  def self.top(n)
   sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating||0) }
   sorted_by_rating_in_desc_order.first(n)
   # palauta listalta parhaat n kappaletta
   # miten? ks. http://www.ruby-doc.org/core-2.1.0/Array.html
  end



=begin Siirretty moduliin /lib kansioon
	def average_rating
		ratings.average(:score)
	end
=end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  #korvataan basic authentication
  #before_action :authenticate, only: [:destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  def list
  end
  

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all

    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    
    order = params[:order] || 'name'
    last_order = session[:last_order]

    if order=='name' && last_order=='name'

      @active_breweries = @active_breweries.sort_by{ |b| b.name }.reverse
      @retired_breweries = @retired_breweries.sort_by{ |b| b.name }.reverse
      session[:last_order] = ''
    
    elsif order=='year' && last_order=='year'
      @active_breweries = @active_breweries.sort_by{ |b| b.year }.reverse
      @retired_breweries = @retired_breweries.sort_by{ |b| b.year }.reverse
      session[:last_order] = ''        
    else
      
      @active_breweries = case order      
        when 'name' then @active_breweries.sort_by{ |b| b.name }        
        when 'year' then @active_breweries.sort_by{ |b| b.year }        
      end
      
      @retired_breweries = case order
        when 'name' then @retired_breweries.sort_by{ |b| b.name }
        when 'year' then @retired_breweries.sort_by{ |b| b.year } 
      end
      
    session[:last_order] = order

    end
  end
        

    #render :panimot
  

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)    

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activitys status changed to #{new_status}"
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

end
=begin
    def authenticate
      admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}
      authenticate_or_request_with_http_basic do |username, password|
        #username == "admin" and password == "secret" blaa
        username == username and password == admin_accounts[username]
    end

  end
=end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:"name") %></th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<h2>Active</h2>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<br>

<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-primary"  %>

app/views/breweries/list.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>
<script>

var myApp = angular.module('myApp', []);

myApp.controller("BreweriesController", function ($scope, $http) {
	$http.get('breweries.json').success( function(data, status, headers, config) {
		$scope.breweries = data;
	});

	$scope.order = 'name';
	$scope.sort_by = function (order) {
		$scope.order = order;

	}

});


</script>

<h2>Brewery list</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

<table class="table table-hover">
	<thead>
		<th><a href="#" ng-click="sort_by('name')">Name</a></th>
		<th><a href="#" ng-click="sort_by('year')">Year</a></th>
		<th><a href="#" ng-click="sort_by('beer.count')">Beers</a></th>
	</thead>
	<tr ng-repeat="brewery in breweries | orderBy:order">
		<td>{{brewery.name}}</td>
		<td>{{brewery.year}}</td>
		<td>{{brewery.beer.count}}</td>
	</tr>

</table>





</div>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

<p>
  <!-- <strong>Name:</strong> -->
  <h2><%= @brewery.name %></h2>
    <% if not @brewery.active %>
      <span class="label label-info">retired</span>
    <% end %>
</p>

<p>
  <!-- <strong>Year:</strong> -->
  <i>Established at <%= @brewery.year %></i>
</p>

<p>Number of beers	
<%= @brewery.beers.count %>
</p>

<p>
<% @brewery.beers.each do |beer| %>
  <%= link_to beer.name, beer %>
  <% end %>
</p>

<p>
  <% if @brewery.ratings.empty? %>
   no ratings
  <% else %>
  Has <%= pluralize(@brewery.ratings.count, 'rating') %>,
   average <%= round(@brewery.average_rating) %>
  <% end %>
</p>

<% end %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>

<!--<%= link_to 'List of beers', beers_path %> | -->
<!--<%= link_to 'Edit', edit_brewery_path(@brewery) %> | -->
<!-- <%= link_to 'Back', breweries_path %> -->
<%= edit_and_destroy_buttons(@brewery) %>